import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

export default async function Home() {
  const hasSupabase = Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL ?? process.env.SUPABASE_URL) && Boolean(process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY);
  if (!hasSupabase) return <main className="landing"><p className="eyebrow">MCL CONTROL PLANE</p><h1>Supabase connection is being provisioned.</h1><p className="hero-copy">The control plane is ready, but the connected Supabase environment is not available to this preview process yet.</p></main>;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return <main className="landing"><p className="eyebrow">MCL CONTROL PLANE</p><h1>Your Minecraft server. Your hardware.</h1><p className="hero-copy">A secure Vercel control panel for Minecraft servers running locally on Windows or Linux. No paid VM required.</p><Link className="button-link" href="/login">Sign in to continue</Link><div className="feature-grid"><article><strong>Outbound agent</strong><span>Your device connects out; no router management port required.</span></article><article><strong>Real status</strong><span>Offline means the local agent is unreachable, never an optimistic fake.</span></article><article><strong>Isolated ownership</strong><span>Supabase RLS keeps every server and agent scoped to its owner.</span></article></div></main>;

  const { data: servers, error } = await supabase.from("servers").select("id,name,minecraft_version,server_software,agent_id,created_at").order("created_at", { ascending: false });
  return <main><header className="topbar"><div><p className="eyebrow">MCL CONTROL PLANE</p><h1>Dashboard</h1></div><form action="/auth/signout" method="post"><button className="secondary">Sign out</button></form></header><section className="hero-panel"><div><span className="status-pill"><i /> Agent network</span><h2>Run Minecraft on your own device.</h2><p>Install the local Server Agent, register it here, and manage Paper, Geyser, Floodgate, logs, backups, and safe commands from one place.</p></div><Link className="button-link" href="/dashboard/agents">Connect an agent</Link></section><section className="section-heading"><div><p className="eyebrow">YOUR INFRASTRUCTURE</p><h2>Servers</h2></div><Link className="button-link" href="/dashboard/servers/new">New server</Link></section>{error ? <div className="notice error">Database is not ready yet: {error.message}</div> : null}{servers?.length ? <div className="server-grid">{servers.map((server) => <article className="server-card" key={server.id}><div className="card-heading"><div><h3>{server.name}</h3><p>{server.server_software} · Minecraft {server.minecraft_version}</p></div><span className="status-pill muted"><i /> Awaiting agent</span></div><div className="card-stats"><span>Players <b>—</b></span><span>CPU <b>—</b></span><span>RAM <b>—</b></span></div><Link href={`/dashboard/servers/${server.id}`}>Open server</Link></article>)}</div> : <div className="empty-state"><h3>No servers yet</h3><p>Create a server record after connecting the agent that runs Minecraft on your device.</p><Link className="button-link" href="/dashboard/agents">Connect your first agent</Link></div>}</main>;
}
